on: pull_request

name: Inspections

jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Exclude specific JavaScript files from PHPCS inspection
        run: |
          find . -type f \( -name "*.js" -o -name "webpack.config.js" \) > .phpcsignore

      - name: Run PHPCS inspection with specific exclusions
        uses: rtCamp/action-phpcs-code-review@v3
        env:
          GH_BOT_TOKEN: ${{ secrets.PHPCS_SCAN }}
        with:
          args: "WordPressVIPMinimum,WordPress,WordPress-Core,WordPress-Docs --ignore=./.phpcsignore"
